// <auto-generated />
using System;
using KoiFishCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KoiFishCare.Migrations
{
    [DbContext(typeof(KoiFishVeterinaryServiceContext))]
    [Migration("20240926020153_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KoiFishCare.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateOnly?>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DistanceID")
                        .HasColumnType("int");

                    b.Property<int?>("KoiOrPoolID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<int?>("SlotID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("VetID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BookingID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("DistanceID");

                    b.HasIndex("KoiOrPoolID");

                    b.HasIndex("PaymentID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("SlotID");

                    b.HasIndex("VetID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("KoiFishCare.Models.Distance", b =>
                {
                    b.Property<int>("DistanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistanceID"));

                    b.Property<decimal>("Kilometer")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("DistanceID");

                    b.ToTable("Distances");

                    b.HasData(
                        new
                        {
                            DistanceID = 1,
                            Kilometer = 5.0m,
                            Price = 20.00m
                        },
                        new
                        {
                            DistanceID = 2,
                            Kilometer = 15.0m,
                            Price = 50.00m
                        });
                });

            modelBuilder.Entity("KoiFishCare.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackID"));

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.HasKey("FeedbackID");

                    b.HasIndex("BookingID");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("KoiFishCare.Models.KoiOrPool", b =>
                {
                    b.Property<int>("KoiOrPoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoiOrPoolID"));

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPool")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KoiOrPoolID");

                    b.HasIndex("CustomerId");

                    b.ToTable("KoiOrPools");

                    b.HasData(
                        new
                        {
                            KoiOrPoolID = 1,
                            CustomerId = "c1",
                            Description = "A beautiful koi pond owned by John.",
                            IsPool = false,
                            Name = "John's Koi Pond"
                        },
                        new
                        {
                            KoiOrPoolID = 2,
                            CustomerId = "c2",
                            Description = "A large swimming pool owned by the Smith family.",
                            IsPool = true,
                            Name = "Smith's Pool"
                        });
                });

            modelBuilder.Entity("KoiFishCare.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<string>("Qrcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentID = 1,
                            Qrcode = "qrcode1",
                            Type = "Credit Card"
                        },
                        new
                        {
                            PaymentID = 2,
                            Qrcode = "qrcode2",
                            Type = "PayPal"
                        });
                });

            modelBuilder.Entity("KoiFishCare.Models.PrescriptionRecord", b =>
                {
                    b.Property<int?>("PrescriptionRecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PrescriptionRecordID"));

                    b.Property<int?>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("DiseaseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionRecordID");

                    b.HasIndex("BookingID");

                    b.ToTable("PrescriptionRecords");
                });

            modelBuilder.Entity("KoiFishCare.Models.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EstimatedDuration")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            Description = "A general health check for Koi fish.",
                            EstimatedDuration = 1.5,
                            Price = 150.00m,
                            ServiceName = "Koi Health Check"
                        },
                        new
                        {
                            ServiceID = 2,
                            Description = "Comprehensive pool maintenance service.",
                            EstimatedDuration = 2.0,
                            Price = 250.00m,
                            ServiceName = "Pool Maintenance"
                        });
                });

            modelBuilder.Entity("KoiFishCare.Models.Slot", b =>
                {
                    b.Property<int>("SlotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotID"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("WeekDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlotID");

                    b.ToTable("Slots");

                    b.HasData(
                        new
                        {
                            SlotID = 1,
                            EndTime = new TimeOnly(10, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0),
                            WeekDate = "Monday"
                        },
                        new
                        {
                            SlotID = 2,
                            EndTime = new TimeOnly(12, 0, 0),
                            StartTime = new TimeOnly(11, 0, 0),
                            WeekDate = "Monday"
                        });
                });

            modelBuilder.Entity("KoiFishCare.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("KoiFishCare.Models.VetSlot", b =>
                {
                    b.Property<string>("VetID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SlotID")
                        .HasColumnType("int");

                    b.Property<bool>("isBooked")
                        .HasColumnType("bit");

                    b.HasKey("VetID", "SlotID");

                    b.HasIndex("SlotID");

                    b.ToTable("VetSlots");

                    b.HasData(
                        new
                        {
                            VetID = "v1",
                            SlotID = 1,
                            isBooked = false
                        },
                        new
                        {
                            VetID = "v2",
                            SlotID = 2,
                            isBooked = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c5986857-52c2-4b75-a4e3-133e8a4e8c2f",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "84ff2cdb-cd7e-4766-9715-1d8c28117359",
                            Name = "Vet",
                            NormalizedName = "VET"
                        },
                        new
                        {
                            Id = "b881b784-3f01-47bd-9258-a8ca762e2b7f",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "708341fb-a15d-4611-ab18-80dfab73a07b",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KoiFishCare.Models.Customer", b =>
                {
                    b.HasBaseType("KoiFishCare.Models.User");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c1",
                            AccessFailedCount = 0,
                            Address = "789 Customer Lane",
                            ConcurrencyStamp = "128791e5-32bb-458b-b43d-1fd28f64424d",
                            EmailConfirmed = false,
                            FirstName = "Alice",
                            Gender = false,
                            ImagePublicId = "customer1_image_id",
                            ImageURL = "https://example.com/customer1.jpg",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedUserName = "ALICU",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3d12b45b-f847-4159-b136-68daa45920f6",
                            TwoFactorEnabled = false,
                            UserName = "alicu"
                        },
                        new
                        {
                            Id = "c2",
                            AccessFailedCount = 0,
                            Address = "123 Customer Ave",
                            ConcurrencyStamp = "ae5ea5d9-0c13-42a0-a573-f75a1d79a7ff",
                            EmailConfirmed = false,
                            FirstName = "Bob",
                            Gender = true,
                            ImagePublicId = "customer2_image_id",
                            ImageURL = "https://example.com/customer2.jpg",
                            LastName = "Williams",
                            LockoutEnabled = false,
                            NormalizedUserName = "BOOOOOB",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a4978c4-ef72-4791-b5eb-3fd40d224b0a",
                            TwoFactorEnabled = false,
                            UserName = "boooob"
                        });
                });

            modelBuilder.Entity("KoiFishCare.Models.Staff", b =>
                {
                    b.HasBaseType("KoiFishCare.Models.User");

                    b.Property<bool?>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerID")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Staffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "s1",
                            AccessFailedCount = 0,
                            Address = "789 Staff Lane",
                            ConcurrencyStamp = "df61ed50-f91f-46ec-a39e-11d88a40d3a7",
                            EmailConfirmed = false,
                            FirstName = "staff1",
                            Gender = false,
                            ImagePublicId = "staff_image_id",
                            ImageURL = "https://example.com/staff1.jpg",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedUserName = "SITAP",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4cb783a9-ef38-477a-93d5-ff67d9bcd38b",
                            TwoFactorEnabled = false,
                            UserName = "sitap",
                            IsManager = false
                        },
                        new
                        {
                            Id = "m2",
                            AccessFailedCount = 0,
                            Address = "123 Staff Ave",
                            ConcurrencyStamp = "19bb7de3-6974-40d5-a141-74c1cc990bee",
                            EmailConfirmed = false,
                            FirstName = "manager",
                            Gender = true,
                            ImagePublicId = "staff2_image_id",
                            ImageURL = "https://example.com/staff2.jpg",
                            LastName = "Williams",
                            LockoutEnabled = false,
                            NormalizedUserName = "MANAGER",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fa201883-f2b5-4895-82d8-482d55d5e30a",
                            TwoFactorEnabled = false,
                            UserName = "manager",
                            IsManager = true
                        });
                });

            modelBuilder.Entity("KoiFishCare.Models.Veterinarian", b =>
                {
                    b.HasBaseType("KoiFishCare.Models.User");

                    b.ToTable("Veterinarians", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "v1",
                            AccessFailedCount = 0,
                            Address = "123 Vet St.",
                            ConcurrencyStamp = "7f55b7b8-6c4d-48cf-b5c2-99a24566bfd5",
                            EmailConfirmed = false,
                            ExperienceYears = 10,
                            FirstName = "John",
                            Gender = true,
                            ImagePublicId = "vet1_image_id",
                            ImageURL = "https://example.com/vet1.jpg",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedUserName = "JOHNDOE",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c30820ae-3d0c-4809-9190-aaf6115fce77",
                            TwoFactorEnabled = false,
                            UserName = "johndoe"
                        },
                        new
                        {
                            Id = "v2",
                            AccessFailedCount = 0,
                            Address = "456 Vet St.",
                            ConcurrencyStamp = "71a35118-5a70-4694-a5e6-b7d48c23ed17",
                            EmailConfirmed = false,
                            ExperienceYears = 8,
                            FirstName = "Jane",
                            Gender = false,
                            ImagePublicId = "vet2_image_id",
                            ImageURL = "https://example.com/vet2.jpg",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedUserName = "JANESMITH",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f3ce81ac-9742-4cf0-aae6-92acb1d1a481",
                            TwoFactorEnabled = false,
                            UserName = "janesmith"
                        });
                });

            modelBuilder.Entity("KoiFishCare.Models.Booking", b =>
                {
                    b.HasOne("KoiFishCare.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiFishCare.Models.Distance", "Distance")
                        .WithMany("Bookings")
                        .HasForeignKey("DistanceID");

                    b.HasOne("KoiFishCare.Models.KoiOrPool", "KoiOrPool")
                        .WithMany("Bookings")
                        .HasForeignKey("KoiOrPoolID");

                    b.HasOne("KoiFishCare.Models.Payment", "Payment")
                        .WithMany("Bookings")
                        .HasForeignKey("PaymentID");

                    b.HasOne("KoiFishCare.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceID");

                    b.HasOne("KoiFishCare.Models.Slot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotID");

                    b.HasOne("KoiFishCare.Models.Veterinarian", "Veterinarian")
                        .WithMany("Bookings")
                        .HasForeignKey("VetID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Distance");

                    b.Navigation("KoiOrPool");

                    b.Navigation("Payment");

                    b.Navigation("Service");

                    b.Navigation("Slot");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("KoiFishCare.Models.Feedback", b =>
                {
                    b.HasOne("KoiFishCare.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingID");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("KoiFishCare.Models.KoiOrPool", b =>
                {
                    b.HasOne("KoiFishCare.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KoiFishCare.Models.PrescriptionRecord", b =>
                {
                    b.HasOne("KoiFishCare.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingID");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("KoiFishCare.Models.VetSlot", b =>
                {
                    b.HasOne("KoiFishCare.Models.Slot", "Slot")
                        .WithMany("VetSlots")
                        .HasForeignKey("SlotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiFishCare.Models.Veterinarian", "Veterinarian")
                        .WithMany("VetSlots")
                        .HasForeignKey("VetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KoiFishCare.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KoiFishCare.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KoiFishCare.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KoiFishCare.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFishCare.Models.Customer", b =>
                {
                    b.HasOne("KoiFishCare.Models.User", null)
                        .WithOne()
                        .HasForeignKey("KoiFishCare.Models.Customer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFishCare.Models.Staff", b =>
                {
                    b.HasOne("KoiFishCare.Models.User", null)
                        .WithOne()
                        .HasForeignKey("KoiFishCare.Models.Staff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFishCare.Models.Veterinarian", b =>
                {
                    b.HasOne("KoiFishCare.Models.User", null)
                        .WithOne()
                        .HasForeignKey("KoiFishCare.Models.Veterinarian", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KoiFishCare.Models.Distance", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("KoiFishCare.Models.KoiOrPool", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("KoiFishCare.Models.Payment", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("KoiFishCare.Models.Service", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("KoiFishCare.Models.Slot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("VetSlots");
                });

            modelBuilder.Entity("KoiFishCare.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("KoiFishCare.Models.Veterinarian", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("VetSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
